server:
  port: 8082

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/instagram_posts

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: post-service
        health-check-interval: 10s

logging:
  level:
    com.instagram.post: DEBUG
    org.springframework.data.mongodb: DEBUG
