server:
  port: 8082

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/instagram_posts

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: post-service
        health-check-interval: 10s

# Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      followService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  level:
    com.instagram.post: DEBUG
    org.springframework.data.mongodb: DEBUG
